### ISSUE TITLE
Links on generated reference pages link to GitHub instead of GitBook

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#292]
See https://app.gitbook.com/o/jhFodLh6YFJJYK6Lv9wE/s/ADj4uhM7zWsbPKzLTjhZ/~/revisions/i8iKVOhcZBt6hcSnYnuZ/api-clients/access-control-systems/systems/list

**Comment by mikewuu** [comment]
I ran `npm run build` but get an empty generated file in  **generated-docs/sdk/javascript/acs/systems/list.md**

![CleanShot 2024-08-13 at 01 10 59@2x](https://github.com/user-attachments/assets/c4a77ad0-a96d-4355-8d48-baea1beb3b68)

Am I missing a step?

**Comment by razor-x** [comment]
@mikewuu SDK pages are not templated yet. We're only working on /api first.

**Comment by razor-x** [comment]
Also, we are working off the beta branch: https://github.com/seamapi/docs/blob/beta/docs/api/acs/systems/list.md

**Comment by mikewuu** [comment]
@razor-x aren't the links suppoesd to be relative (so they link to github)? Here's a file on `main` that isn't generated that shows they link to github too

https://github.com/seamapi/docs/blob/beta/docs/capability-guides/access-systems/assigning-credentials-to-users.md

**Comment by razor-x** [comment]
@mikewuu They are supposed to link to gitbook when looking on the gitbook hosted version.

**Comment by razor-x** [comment]
Lets revisit this one after we do these two, it might fix the issue 🤷 

- https://github.com/seamapi/docs/issues/303
- https://github.com/seamapi/docs/issues/304
