### ISSUE TITLE
Generate all endpoints under the /acs/systems routes

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#299]
Here is an outline for what we want to generate `/

````md
# List ACS Systems

```
GET /acs/systems/list ⇒ { acs_systems: [acs_system, …] }
```

Returns a list of all [access control systems](../../../capability-guides/access-systems.md).

*Return Type: Array<[acs_system](../README.md)>*

{% tabs %}
// code sample
{% endtabs %}

## Request Parameters

### `connected_account_id`

*Type:* `string`  
*Required:* No

ID of the connected account by which to filter the list of returned access control systems.

---
````

**Comment by razor-x** [comment]
Note that at the moment, we only have one code sample per endpoint, however we plan to add multiple samples: one "simple" one that is always at the top, and then other cases that will appear on the page (location TBD). This is out of scope for now: just render all code samples with a loop at the top.

**Comment by andrii-balitskyi** [comment]
Implemented in https://github.com/seamapi/docs/pull/311
