### ISSUE TITLE
Generate /docs/acs/systems/README.md with acs_system resource and properties

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#300]
Note the content is just an example to demonstrate the format, e.g., acs_system_id is not actually deprecated.

````md
Description here, but not supported yet (see https://github.com/seamapi/docs/issues/305)

## acs_system

### acs_system_id

{% hint style="warning" %}
**Deprecated** use something else.
{% endhint %}

ID of the `acs_system`.

Type: `string`
Format: `uuid`
---

## Endpoints

### [/acs/systems/list]()

List ACS Systems.

### [/acs/systems/get]()

Get an ACS System.

## Events

### acs_system.connected

An ACS system was connected.

#### acs_system_id

ID of the `acs_system`

#### created_at

When the event was created.
---
```

**Comment by razor-x** [comment]
@DebbieAtSeam Should we prefer using "code" in titles or normal? E.g.,


```
### `/acs/systems/list`
### `acs_system_id`
### `acs_system`
### `acs_system.connected`
```

or 

```
### /acs/systems/list
### acs_system_id
### acs_system
### acs_system.connected
```

**Comment by razor-x** [comment]
We want to include events on this page, but the first version does not need to include events (we will need to make sure blueprint supports what we want).

**Comment by razor-x** [comment]
Open question: how to map which resources should be included on the README.md pages? This is more "metadata" for routes and namespaces which we can't support in blueprint yet, so we can start by using https://github.com/seamapi/docs/issues/305.

For now, we can just hard code a filter for `acs_system`

**Comment by DebbieAtSeam** [comment]
> @DebbieAtSeam Should we prefer using "code" in titles or normal? E.g.,
> 
> 
> 
> 
> 
> ```
> 
> ### `/acs/systems/list`
> 
> ### `acs_system_id`
> 
> ### `acs_system`
> 
> ### `acs_system.connected`
> 
> ```
> 
> 
> 
> or 
> 
> 
> 
> ```
> 
> ### /acs/systems/list
> 
> ### acs_system_id
> 
> ### acs_system
> 
> ### acs_system.connected
> 
> ```

@razor-x I vote for code.
