### ISSUE TITLE
Add code samples to all /acs/systems pages

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#324]
See https://github.com/seamapi/docs/blob/main/src/data/code-sample-definitions/acs-systems.yaml

Need:

- [ ] /acs/systems/get
- [ ] /acs/systems/list_compatible_credential_manager_acs_systems

**Comment by DebbieAtSeam** [comment]
@razor-x Is it true that I should add all the code samples for all acs_systems endpoints to this one file? https://github.com/seamapi/docs/blob/main/src/data/code-sample-definitions/acs-systems.yaml
Thanks!

**Comment by razor-x** [comment]
> @razor-x Is it true that I should add all the code samples for all acs_systems endpoints to this one file? https://github.com/seamapi/docs/blob/main/src/data/code-sample-definitions/acs-systems.yaml
> Thanks!

Yes, but we can structure the files however we like. I figured splitting them up by route would be a good way to go.
