### ISSUE TITLE
Add descriptions and code samples for /thermostats and resources

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#347]
Copy existing descriptions and code samples from the live docs and move them into the zod descriptions and code sample definitions.

- [x] ~~Copy descriptions to resource~~ Resource parameters are currently undefined: https://github.com/seamapi/seam-connect/pull/8833
- [ ] Copy route descriptions to 
- [ ] Copy any existing descriptions of `*_metadata` properties in `public-types/models/acs/metadata`.
- [ ] Add [code samples](https://github.com/seamapi/docs/tree/main/src/data/code-sample-definitions)

**Comment by razor-x** [comment]
Trying to get blueprint working here https://github.com/seamapi/blueprint/pull/87

**Comment by razor-x** [comment]
@mikewuu the first two items were checked when I made the issue but they are not actually done.

**Comment by mikewuu** [comment]
> @mikewuu the first two items were checked when I made the issue but they are not actually done.

oh, thanks, will do this now
