### ISSUE TITLE
Generate documentation report

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#364]
Generate a new file under `/docs/api/_report.md` using a new layout `/src/layouts/report.ts`. This file is not published on gitbook because nothing links to it. 

The report will show us our overall doc coverage and status.

Needs https://github.com/seamapi/blueprint/issues/108

Sample report markdown: 

# Reference Documentation Report

## Undocumented

These items are intentionally undocumented.

### Resources

- `device`: reason...
- `user_identity` : reason...

### Resource properties

- `device.foo`: reason...
- `device.bar`: reason...

### Namespaces / routes / endpoints

- `/devices`: reason...
- `/devices/list`: reason...
- `/acs`: reason...

### Endpoint parameters

- `/devices/list`
    - `connected_account_id`: reason...
    - `device_type`: reason...

## No Description

These items have an empty description.
Items that are intentionally undocumented are not included in this section.

### Resources

- `device`
- `user_identity`

### Resource properties

- `device.foo`
- `device.bar`

### Namespaces / routes / endpoints

- `/devices`
- `/devices/list`
- `/acs`

### Endpoint parameters

- `/devices/list`
    - `connected_account_id`
    - `device_type`

## Draft

These items have been marked as draft.

### Resources

- `device`
- `user_identity`

### Resource properties

- `device.foo`
- `device.bar`

### Namespaces / routes / endpoints

- `/devices`
- `/devices/list`
- `/acs`

### Endpoint parameters

- `/devices/list`
    - `connected_account_id`
    - `device_type`

## Missing `return_type`

These routes are missing a `return_type` and should be fixed.

- `/devices`
- `/devices/list`
- `/acs`

## Deprecated

These items are deprecated.

### Resources

- `device`: reason...
- `user_identity` : reason...

### Resource properties

- `device.foo`: reason...
- `device.bar`: reason...

### Namespaces / routes / endpoints

- `/devices`: reason...
- `/devices/list`: reason...
- `/acs`: reason...

### Endpoint parameters

- `/devices/list`
    - `connected_account_id`: reason...
    - `device_type`: reason...

**Comment by razor-x** [comment]
Note that Events and Action Attempts are out of scope since they are not fully supported by blueprint yet.

**Comment by razor-x** [comment]
@DebbieAtSeam What about number of code samples or routes that are missing code samples?

**Comment by DebbieAtSeam** [comment]
@razor-x You said: What about number of code samples or routes that are missing code samples?
Is it possible to report this info.? If so, routes that have no code samples would be helpful, I think.

Also, what about enums/enum values? Do we need to report on those too?

**Comment by razor-x** [comment]
> Also, what about enums/enum values? Do we need to report on those too?

Sounds good, we can do that under the property, e.g., consider that as missing a description.

**Comment by razor-x** [comment]
@andrii-balitskyi Under deprecated, can we add a section `Response Keys` that shows any endpoints that have extra properties in the response that don't match the `responseKey`?
