### ISSUE TITLE
Generate namespace pages

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#399]
Need add a template for namespaces. For now, GitBook will generate one for us. Once we decide on the content / layout for ACS, we can add the title and description, etc, here: https://github.com/seamapi/docs/blob/main/src/data/paths.yaml

**Comment by razor-x** [comment]
@DebbieAtSeam What content should the namespace page have?

**Comment by DebbieAtSeam** [comment]
@razor-x I suggest something like this... https://github.com/seamapi/docs/blob/b503892611a18089a0a9bacbfbe54c01591a5a5e/docs/api-clients/acs/README.md

**Comment by razor-x** [comment]
@DebbieAtSeam Should we keep the table? I personally prefer a more semantic format. Tables are not great for general accessibility and responsiveness. I think we should generally avoid them unless we actually have tabular data to render.
