### ISSUE TITLE
Add missing titles to the doc report

### ISSUE THREAD

**Issue by razor-x** [seamapi/docs#404]
If any endpoints or routes are missing titles, add that as a section to the `_report.md`. [Filter out generating pages](https://github.com/seamapi/docs/blob/main/src/lib/reference.ts) for anything missing a title.

**Comment by andrii-balitskyi** [comment]
@razor-x Blueprint doesn't define titles for routes and namespaces. We currently define only endpoint titles through the front matter. Where should route and namespace titles come from?

**Comment by razor-x** [comment]
Titles for routes and namespaces are currently defined in path info.

**Comment by andrii-balitskyi** [comment]
@razor-x Am I understanding correctly that a path from `/src/data/paths.yaml` corresponds to a route from Blueprint? How is the namespace title defined?

**Comment by razor-x** [comment]
Namespace pages are not generated yet but they should be https://github.com/seamapi/docs/issues/399

**Comment by andrii-balitskyi** [comment]
I made a PR for endpoint and route titles https://github.com/seamapi/docs/pull/432. I'll create a separate issue for reporting namespace title which can be done when namespace pages are implemented.
